apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: RabbitMQ Management
    type: simpod-json-datasource
    access: proxy
    url: http://rabbitmq:15672
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
    jsonData:
      httpHeaderName1: 'Content-Type'
      httpHeaderValue1: 'application/json'
